/* Generated by Yosys 0.30+38 (git sha1 596da3f2a, gcc 13.1.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -fPIC -Os) */

(* \amaranth.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module top(inp_sel_0, inp_sel_1, outp_hosts_active, outp_devs_active, outp_h2d_conn_arr_0, outp_h2d_conn_arr_1, outp_d2h_conn_arr_0, outp_d2h_conn_arr_1, inp_sel_conn);
  reg \$auto$verilog_backend.cc:2097:dump_module$1  = 0;
  wire \$1 ;
  wire \$11 ;
  wire \$13 ;
  wire \$15 ;
  wire \$17 ;
  wire \$19 ;
  wire \$21 ;
  wire \$23 ;
  wire \$3 ;
  wire \$5 ;
  wire \$7 ;
  wire \$9 ;
  input inp_sel_0;
  wire inp_sel_0;
  input inp_sel_1;
  wire inp_sel_1;
  input [1:0] inp_sel_conn;
  wire [1:0] inp_sel_conn;
  wire [1:0] loc_d2h_found_arr_0;
  wire [1:0] loc_d2h_found_arr_1;
  wire [1:0] loc_h2d_found_arr_0;
  wire [1:0] loc_h2d_found_arr_1;
  output outp_d2h_conn_arr_0;
  reg outp_d2h_conn_arr_0;
  output outp_d2h_conn_arr_1;
  reg outp_d2h_conn_arr_1;
  output [1:0] outp_devs_active;
  wire [1:0] outp_devs_active;
  output outp_h2d_conn_arr_0;
  reg outp_h2d_conn_arr_0;
  output outp_h2d_conn_arr_1;
  reg outp_h2d_conn_arr_1;
  output [1:0] outp_hosts_active;
  wire [1:0] outp_hosts_active;
  assign \$11  = inp_sel_conn[0] &  \$9 ;
  assign \$15  = inp_sel_conn[1] &  \$13 ;
  assign \$17  = |  loc_h2d_found_arr_0;
  assign \$1  = ~  inp_sel_0;
  assign \$19  = |  loc_h2d_found_arr_1;
  assign \$21  = |  loc_d2h_found_arr_0;
  assign \$23  = |  loc_d2h_found_arr_1;
  assign \$3  = inp_sel_conn[0] &  \$1 ;
  assign \$5  = ~  inp_sel_1;
  assign \$7  = inp_sel_conn[1] &  \$5 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$1 ) begin end
    outp_h2d_conn_arr_0 = 1'h0;
    casez (loc_h2d_found_arr_0)
      /* src = "/home/fl4shk/temp_venv/lib/python3.11/site-packages/libcheesevoyage/intrcn_lcv/xbar_switch_mods.py:630" */
      2'b?1:
          outp_h2d_conn_arr_0 = 1'h0;
    endcase
    casez (loc_h2d_found_arr_1)
      /* src = "/home/fl4shk/temp_venv/lib/python3.11/site-packages/libcheesevoyage/intrcn_lcv/xbar_switch_mods.py:630" */
      2'b?1:
          outp_h2d_conn_arr_0 = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$1 ) begin end
    outp_d2h_conn_arr_0 = 1'h0;
    casez (loc_h2d_found_arr_0)
      /* src = "/home/fl4shk/temp_venv/lib/python3.11/site-packages/libcheesevoyage/intrcn_lcv/xbar_switch_mods.py:630" */
      2'b?1:
          outp_d2h_conn_arr_0 = 1'h0;
      /* src = "/home/fl4shk/temp_venv/lib/python3.11/site-packages/libcheesevoyage/intrcn_lcv/xbar_switch_mods.py:630" */
      2'h2:
          outp_d2h_conn_arr_0 = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$1 ) begin end
    outp_h2d_conn_arr_1 = 1'h0;
    casez (loc_h2d_found_arr_0)
      /* src = "/home/fl4shk/temp_venv/lib/python3.11/site-packages/libcheesevoyage/intrcn_lcv/xbar_switch_mods.py:630" */
      2'b?1:
          /* empty */;
      /* src = "/home/fl4shk/temp_venv/lib/python3.11/site-packages/libcheesevoyage/intrcn_lcv/xbar_switch_mods.py:630" */
      2'h2:
          outp_h2d_conn_arr_1 = 1'h0;
    endcase
    casez (loc_h2d_found_arr_1)
      /* src = "/home/fl4shk/temp_venv/lib/python3.11/site-packages/libcheesevoyage/intrcn_lcv/xbar_switch_mods.py:630" */
      2'b?1:
          /* empty */;
      /* src = "/home/fl4shk/temp_venv/lib/python3.11/site-packages/libcheesevoyage/intrcn_lcv/xbar_switch_mods.py:630" */
      2'h2:
          outp_h2d_conn_arr_1 = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$1 ) begin end
    outp_d2h_conn_arr_1 = 1'h0;
    casez (loc_h2d_found_arr_1)
      /* src = "/home/fl4shk/temp_venv/lib/python3.11/site-packages/libcheesevoyage/intrcn_lcv/xbar_switch_mods.py:630" */
      2'b?1:
          outp_d2h_conn_arr_1 = 1'h0;
      /* src = "/home/fl4shk/temp_venv/lib/python3.11/site-packages/libcheesevoyage/intrcn_lcv/xbar_switch_mods.py:630" */
      2'h2:
          outp_d2h_conn_arr_1 = 1'h1;
    endcase
  end
  assign outp_hosts_active[1] = \$23 ;
  assign outp_hosts_active[0] = \$21 ;
  assign outp_devs_active[1] = \$19 ;
  assign outp_devs_active[0] = \$17 ;
  assign loc_h2d_found_arr_1[1] = \$15 ;
  assign loc_h2d_found_arr_1[0] = \$11 ;
  assign loc_d2h_found_arr_1[1] = loc_h2d_found_arr_1[1];
  assign loc_d2h_found_arr_1[0] = loc_h2d_found_arr_0[1];
  assign loc_d2h_found_arr_0[1] = loc_h2d_found_arr_1[0];
  assign loc_d2h_found_arr_0[0] = loc_h2d_found_arr_0[0];
  assign loc_h2d_found_arr_0[1] = \$7 ;
  assign loc_h2d_found_arr_0[0] = \$3 ;
  assign \$9  = inp_sel_0;
  assign \$13  = inp_sel_1;
endmodule

