/* Generated by Yosys 0.30+38 (git sha1 596da3f2a, gcc 13.1.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -fPIC -Os) */

(* \amaranth.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module top(inp_sel_0, inp_sel_1, inp_sel_2, outp_hosts_active, outp_devs_active, outp_h2d_conn_arr_0, outp_h2d_conn_arr_1, outp_h2d_conn_arr_2, outp_d2h_conn_arr_0, outp_d2h_conn_arr_1, inp_sel_conn);
  reg \$auto$verilog_backend.cc:2097:dump_module$1  = 0;
  wire \$1 ;
  wire \$11 ;
  wire \$13 ;
  wire \$15 ;
  wire \$17 ;
  wire \$19 ;
  wire \$21 ;
  wire \$23 ;
  wire \$25 ;
  wire \$27 ;
  wire \$29 ;
  wire \$3 ;
  wire \$31 ;
  wire \$33 ;
  wire \$5 ;
  wire \$7 ;
  wire \$9 ;
  input inp_sel_0;
  wire inp_sel_0;
  input inp_sel_1;
  wire inp_sel_1;
  input inp_sel_2;
  wire inp_sel_2;
  input [2:0] inp_sel_conn;
  wire [2:0] inp_sel_conn;
  wire [1:0] loc_d2h_found_arr_0;
  wire [1:0] loc_d2h_found_arr_1;
  wire [1:0] loc_d2h_found_arr_2;
  wire [2:0] loc_h2d_found_arr_0;
  wire [2:0] loc_h2d_found_arr_1;
  output [1:0] outp_d2h_conn_arr_0;
  reg [1:0] outp_d2h_conn_arr_0;
  output [1:0] outp_d2h_conn_arr_1;
  reg [1:0] outp_d2h_conn_arr_1;
  output [1:0] outp_devs_active;
  wire [1:0] outp_devs_active;
  output outp_h2d_conn_arr_0;
  reg outp_h2d_conn_arr_0;
  output outp_h2d_conn_arr_1;
  reg outp_h2d_conn_arr_1;
  output outp_h2d_conn_arr_2;
  reg outp_h2d_conn_arr_2;
  output [2:0] outp_hosts_active;
  wire [2:0] outp_hosts_active;
  assign \$9  = ~  inp_sel_2;
  assign \$11  = inp_sel_conn[2] &  \$9 ;
  assign \$15  = inp_sel_conn[0] &  \$13 ;
  assign \$1  = ~  inp_sel_0;
  assign \$19  = inp_sel_conn[1] &  \$17 ;
  assign \$23  = inp_sel_conn[2] &  \$21 ;
  assign \$25  = |  loc_h2d_found_arr_0;
  assign \$27  = |  loc_h2d_found_arr_1;
  assign \$29  = |  loc_d2h_found_arr_0;
  assign \$31  = |  loc_d2h_found_arr_1;
  assign \$33  = |  loc_d2h_found_arr_2;
  assign \$3  = inp_sel_conn[0] &  \$1 ;
  assign \$5  = ~  inp_sel_1;
  assign \$7  = inp_sel_conn[1] &  \$5 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$1 ) begin end
    outp_h2d_conn_arr_0 = 1'h0;
    casez (loc_h2d_found_arr_0)
      /* src = "/home/fl4shk/temp_venv/lib/python3.11/site-packages/libcheesevoyage/intrcn_lcv/xbar_switch_mods.py:630" */
      3'b??1:
          outp_h2d_conn_arr_0 = 1'h0;
    endcase
    casez (loc_h2d_found_arr_1)
      /* src = "/home/fl4shk/temp_venv/lib/python3.11/site-packages/libcheesevoyage/intrcn_lcv/xbar_switch_mods.py:630" */
      3'b??1:
          outp_h2d_conn_arr_0 = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$1 ) begin end
    outp_d2h_conn_arr_0 = 2'h0;
    casez (loc_h2d_found_arr_0)
      /* src = "/home/fl4shk/temp_venv/lib/python3.11/site-packages/libcheesevoyage/intrcn_lcv/xbar_switch_mods.py:630" */
      3'b??1:
          outp_d2h_conn_arr_0 = 2'h0;
      /* src = "/home/fl4shk/temp_venv/lib/python3.11/site-packages/libcheesevoyage/intrcn_lcv/xbar_switch_mods.py:630" */
      3'b?10:
          outp_d2h_conn_arr_0 = 2'h1;
      /* src = "/home/fl4shk/temp_venv/lib/python3.11/site-packages/libcheesevoyage/intrcn_lcv/xbar_switch_mods.py:630" */
      3'h4:
          outp_d2h_conn_arr_0 = 2'h2;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$1 ) begin end
    outp_h2d_conn_arr_1 = 1'h0;
    casez (loc_h2d_found_arr_0)
      /* src = "/home/fl4shk/temp_venv/lib/python3.11/site-packages/libcheesevoyage/intrcn_lcv/xbar_switch_mods.py:630" */
      3'b??1:
          /* empty */;
      /* src = "/home/fl4shk/temp_venv/lib/python3.11/site-packages/libcheesevoyage/intrcn_lcv/xbar_switch_mods.py:630" */
      3'b?10:
          outp_h2d_conn_arr_1 = 1'h0;
    endcase
    casez (loc_h2d_found_arr_1)
      /* src = "/home/fl4shk/temp_venv/lib/python3.11/site-packages/libcheesevoyage/intrcn_lcv/xbar_switch_mods.py:630" */
      3'b??1:
          /* empty */;
      /* src = "/home/fl4shk/temp_venv/lib/python3.11/site-packages/libcheesevoyage/intrcn_lcv/xbar_switch_mods.py:630" */
      3'b?10:
          outp_h2d_conn_arr_1 = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$1 ) begin end
    outp_h2d_conn_arr_2 = 1'h0;
    casez (loc_h2d_found_arr_0)
      /* src = "/home/fl4shk/temp_venv/lib/python3.11/site-packages/libcheesevoyage/intrcn_lcv/xbar_switch_mods.py:630" */
      3'b??1:
          /* empty */;
      /* src = "/home/fl4shk/temp_venv/lib/python3.11/site-packages/libcheesevoyage/intrcn_lcv/xbar_switch_mods.py:630" */
      3'b?10:
          /* empty */;
      /* src = "/home/fl4shk/temp_venv/lib/python3.11/site-packages/libcheesevoyage/intrcn_lcv/xbar_switch_mods.py:630" */
      3'h4:
          outp_h2d_conn_arr_2 = 1'h0;
    endcase
    casez (loc_h2d_found_arr_1)
      /* src = "/home/fl4shk/temp_venv/lib/python3.11/site-packages/libcheesevoyage/intrcn_lcv/xbar_switch_mods.py:630" */
      3'b??1:
          /* empty */;
      /* src = "/home/fl4shk/temp_venv/lib/python3.11/site-packages/libcheesevoyage/intrcn_lcv/xbar_switch_mods.py:630" */
      3'b?10:
          /* empty */;
      /* src = "/home/fl4shk/temp_venv/lib/python3.11/site-packages/libcheesevoyage/intrcn_lcv/xbar_switch_mods.py:630" */
      3'h4:
          outp_h2d_conn_arr_2 = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2097:dump_module$1 ) begin end
    outp_d2h_conn_arr_1 = 2'h0;
    casez (loc_h2d_found_arr_1)
      /* src = "/home/fl4shk/temp_venv/lib/python3.11/site-packages/libcheesevoyage/intrcn_lcv/xbar_switch_mods.py:630" */
      3'b??1:
          outp_d2h_conn_arr_1 = 2'h0;
      /* src = "/home/fl4shk/temp_venv/lib/python3.11/site-packages/libcheesevoyage/intrcn_lcv/xbar_switch_mods.py:630" */
      3'b?10:
          outp_d2h_conn_arr_1 = 2'h1;
      /* src = "/home/fl4shk/temp_venv/lib/python3.11/site-packages/libcheesevoyage/intrcn_lcv/xbar_switch_mods.py:630" */
      3'h4:
          outp_d2h_conn_arr_1 = 2'h2;
    endcase
  end
  assign outp_hosts_active[2] = \$33 ;
  assign outp_hosts_active[1] = \$31 ;
  assign outp_hosts_active[0] = \$29 ;
  assign outp_devs_active[1] = \$27 ;
  assign outp_devs_active[0] = \$25 ;
  assign loc_h2d_found_arr_1[2] = \$23 ;
  assign loc_h2d_found_arr_1[1] = \$19 ;
  assign loc_h2d_found_arr_1[0] = \$15 ;
  assign loc_d2h_found_arr_2[1] = loc_h2d_found_arr_1[2];
  assign loc_d2h_found_arr_2[0] = loc_h2d_found_arr_0[2];
  assign loc_d2h_found_arr_1[1] = loc_h2d_found_arr_1[1];
  assign loc_d2h_found_arr_1[0] = loc_h2d_found_arr_0[1];
  assign loc_d2h_found_arr_0[1] = loc_h2d_found_arr_1[0];
  assign loc_d2h_found_arr_0[0] = loc_h2d_found_arr_0[0];
  assign loc_h2d_found_arr_0[2] = \$11 ;
  assign loc_h2d_found_arr_0[1] = \$7 ;
  assign loc_h2d_found_arr_0[0] = \$3 ;
  assign \$13  = inp_sel_0;
  assign \$17  = inp_sel_1;
  assign \$21  = inp_sel_2;
endmodule

