/* Generated by Yosys 0.30+48 (git sha1 14d50a176, gcc 13.1.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -fPIC -Os) */

(* dynports =  1  *)
(* cells_not_processed =  1  *)
(* src = "long_div_mods_test.v:1.1-81.10" *)
module Top(clk, rst, inp_valid, inp_numer, inp_denom, inp_is_signed, outp_ready, outp_quot, outp_rema);
  (* src = "long_div_mods_test.v:62.5-68.55" *)
  wire [7:0] _00_;
  (* src = "long_div_mods_test.v:62.5-68.55" *)
  wire _01_;
  (* src = "long_div_mods_test.v:62.5-68.55" *)
  wire [7:0] _02_;
  (* src = "long_div_mods_test.v:62.5-68.55" *)
  wire [7:0] _03_;
  (* src = "long_div_mods_test.v:62.5-68.55" *)
  wire _04_;
  (* src = "long_div_mods_test.v:62.5-68.55" *)
  wire [7:0] _05_;
  (* src = "long_div_mods_test.v:62.5-68.55" *)
  wire [7:0] _06_;
  (* src = "long_div_mods_test.v:62.5-68.55" *)
  wire _07_;
  (* src = "long_div_mods_test.v:62.5-68.55" *)
  wire [7:0] _08_;
  wire [7:0] _09_;
  wire _10_;
  wire [7:0] _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire [7:0] _17_;
  wire _18_;
  wire [7:0] _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire [7:0] _25_;
  wire _26_;
  wire [7:0] _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  (* src = "long_div_mods_test.v:16.13-16.16" *)
  input clk;
  wire clk;
  (* src = "long_div_mods_test.v:33.10-33.13" *)
  wire \gen_for_loop[0].div_intf.clk ;
  (* src = "long_div_mods_test.v:74.11-74.25" *)
  wire \gen_for_loop[0].div_intf.denom ;
  (* src = "long_div_mods_test.v:49.29-49.33" *)
  reg [7:0] \gen_for_loop[0].div_intf.from.quot ;
  (* src = "long_div_mods_test.v:48.10-48.15" *)
  reg \gen_for_loop[0].div_intf.from.ready ;
  (* src = "long_div_mods_test.v:50.29-50.33" *)
  reg [7:0] \gen_for_loop[0].div_intf.from.rema ;
  (* src = "long_div_mods_test.v:75.11-75.29" *)
  wire \gen_for_loop[0].div_intf.is_signed ;
  (* src = "long_div_mods_test.v:73.11-73.25" *)
  wire \gen_for_loop[0].div_intf.numer ;
  (* src = "long_div_mods_test.v:77.47-77.60" *)
  wire \gen_for_loop[0].div_intf.quot ;
  (* src = "long_div_mods_test.v:76.27-76.41" *)
  wire \gen_for_loop[0].div_intf.ready ;
  (* src = "long_div_mods_test.v:78.47-78.60" *)
  wire \gen_for_loop[0].div_intf.rema ;
  (* src = "long_div_mods_test.v:34.10-34.13" *)
  wire \gen_for_loop[0].div_intf.rst ;
  (* src = "long_div_mods_test.v:42.31-42.36" *)
  wire [7:0] \gen_for_loop[0].div_intf.to.denom ;
  (* src = "long_div_mods_test.v:43.11-43.20" *)
  wire \gen_for_loop[0].div_intf.to.is_signed ;
  (* src = "long_div_mods_test.v:41.30-41.35" *)
  wire [7:0] \gen_for_loop[0].div_intf.to.numer ;
  (* src = "long_div_mods_test.v:40.11-40.16" *)
  wire \gen_for_loop[0].div_intf.to.valid ;
  (* src = "long_div_mods_test.v:72.11-72.25" *)
  wire \gen_for_loop[0].div_intf.valid ;
  (* src = "long_div_mods_test.v:33.10-33.13" *)
  wire \gen_for_loop[1].div_intf.clk ;
  (* src = "long_div_mods_test.v:74.11-74.25" *)
  wire \gen_for_loop[1].div_intf.denom ;
  (* src = "long_div_mods_test.v:49.29-49.33" *)
  reg [7:0] \gen_for_loop[1].div_intf.from.quot ;
  (* src = "long_div_mods_test.v:48.10-48.15" *)
  reg \gen_for_loop[1].div_intf.from.ready ;
  (* src = "long_div_mods_test.v:50.29-50.33" *)
  reg [7:0] \gen_for_loop[1].div_intf.from.rema ;
  (* src = "long_div_mods_test.v:75.11-75.29" *)
  wire \gen_for_loop[1].div_intf.is_signed ;
  (* src = "long_div_mods_test.v:73.11-73.25" *)
  wire \gen_for_loop[1].div_intf.numer ;
  (* src = "long_div_mods_test.v:77.47-77.60" *)
  wire \gen_for_loop[1].div_intf.quot ;
  (* src = "long_div_mods_test.v:76.27-76.41" *)
  wire \gen_for_loop[1].div_intf.ready ;
  (* src = "long_div_mods_test.v:78.47-78.60" *)
  wire \gen_for_loop[1].div_intf.rema ;
  (* src = "long_div_mods_test.v:34.10-34.13" *)
  wire \gen_for_loop[1].div_intf.rst ;
  (* src = "long_div_mods_test.v:42.31-42.36" *)
  wire [7:0] \gen_for_loop[1].div_intf.to.denom ;
  (* src = "long_div_mods_test.v:43.11-43.20" *)
  wire \gen_for_loop[1].div_intf.to.is_signed ;
  (* src = "long_div_mods_test.v:41.30-41.35" *)
  wire [7:0] \gen_for_loop[1].div_intf.to.numer ;
  (* src = "long_div_mods_test.v:40.11-40.16" *)
  wire \gen_for_loop[1].div_intf.to.valid ;
  (* src = "long_div_mods_test.v:72.11-72.25" *)
  wire \gen_for_loop[1].div_intf.valid ;
  (* src = "long_div_mods_test.v:33.10-33.13" *)
  wire \gen_for_loop[2].div_intf.clk ;
  (* src = "long_div_mods_test.v:74.11-74.25" *)
  wire \gen_for_loop[2].div_intf.denom ;
  (* src = "long_div_mods_test.v:49.29-49.33" *)
  reg [7:0] \gen_for_loop[2].div_intf.from.quot ;
  (* src = "long_div_mods_test.v:48.10-48.15" *)
  reg \gen_for_loop[2].div_intf.from.ready ;
  (* src = "long_div_mods_test.v:50.29-50.33" *)
  reg [7:0] \gen_for_loop[2].div_intf.from.rema ;
  (* src = "long_div_mods_test.v:75.11-75.29" *)
  wire \gen_for_loop[2].div_intf.is_signed ;
  (* src = "long_div_mods_test.v:73.11-73.25" *)
  wire \gen_for_loop[2].div_intf.numer ;
  (* src = "long_div_mods_test.v:77.47-77.60" *)
  wire \gen_for_loop[2].div_intf.quot ;
  (* src = "long_div_mods_test.v:76.27-76.41" *)
  wire \gen_for_loop[2].div_intf.ready ;
  (* src = "long_div_mods_test.v:78.47-78.60" *)
  wire \gen_for_loop[2].div_intf.rema ;
  (* src = "long_div_mods_test.v:34.10-34.13" *)
  wire \gen_for_loop[2].div_intf.rst ;
  (* src = "long_div_mods_test.v:42.31-42.36" *)
  wire [7:0] \gen_for_loop[2].div_intf.to.denom ;
  (* src = "long_div_mods_test.v:43.11-43.20" *)
  wire \gen_for_loop[2].div_intf.to.is_signed ;
  (* src = "long_div_mods_test.v:41.30-41.35" *)
  wire [7:0] \gen_for_loop[2].div_intf.to.numer ;
  (* src = "long_div_mods_test.v:40.11-40.16" *)
  wire \gen_for_loop[2].div_intf.to.valid ;
  (* src = "long_div_mods_test.v:72.11-72.25" *)
  wire \gen_for_loop[2].div_intf.valid ;
  (* src = "long_div_mods_test.v:20.46-20.55" *)
  input [23:0] inp_denom;
  wire [23:0] inp_denom;
  (* src = "long_div_mods_test.v:21.30-21.43" *)
  input [0:2] inp_is_signed;
  wire [0:2] inp_is_signed;
  (* src = "long_div_mods_test.v:19.45-19.54" *)
  input [23:0] inp_numer;
  wire [23:0] inp_numer;
  (* src = "long_div_mods_test.v:18.30-18.39" *)
  input [0:2] inp_valid;
  wire [0:2] inp_valid;
  (* src = "long_div_mods_test.v:23.46-23.55" *)
  output [23:0] outp_quot;
  wire [23:0] outp_quot;
  (* src = "long_div_mods_test.v:22.31-22.41" *)
  output [0:2] outp_ready;
  wire [0:2] outp_ready;
  (* src = "long_div_mods_test.v:24.46-24.55" *)
  output [23:0] outp_rema;
  wire [23:0] outp_rema;
  (* src = "long_div_mods_test.v:17.13-17.16" *)
  input rst;
  wire rst;
  (* src = "long_div_mods_test.v:62.5-68.55" *)
  always @(posedge \gen_for_loop[2].div_intf.clk )
    \gen_for_loop[2].div_intf.from.ready  <= _31_;
  (* src = "long_div_mods_test.v:62.5-68.55" *)
  always @(posedge \gen_for_loop[2].div_intf.clk )
    \gen_for_loop[2].div_intf.from.quot  <= _09_;
  (* src = "long_div_mods_test.v:62.5-68.55" *)
  always @(posedge \gen_for_loop[2].div_intf.clk )
    \gen_for_loop[2].div_intf.from.rema  <= _11_;
  (* src = "long_div_mods_test.v:62.5-68.55" *)
  always @(posedge \gen_for_loop[1].div_intf.clk )
    \gen_for_loop[1].div_intf.from.ready  <= _15_;
  (* src = "long_div_mods_test.v:62.5-68.55" *)
  always @(posedge \gen_for_loop[1].div_intf.clk )
    \gen_for_loop[1].div_intf.from.quot  <= _17_;
  (* src = "long_div_mods_test.v:62.5-68.55" *)
  always @(posedge \gen_for_loop[1].div_intf.clk )
    \gen_for_loop[1].div_intf.from.rema  <= _19_;
  (* src = "long_div_mods_test.v:62.5-68.55" *)
  always @(posedge \gen_for_loop[0].div_intf.clk )
    \gen_for_loop[0].div_intf.from.ready  <= _23_;
  (* src = "long_div_mods_test.v:62.5-68.55" *)
  always @(posedge \gen_for_loop[0].div_intf.clk )
    \gen_for_loop[0].div_intf.from.quot  <= _25_;
  (* src = "long_div_mods_test.v:62.5-68.55" *)
  always @(posedge \gen_for_loop[0].div_intf.clk )
    \gen_for_loop[0].div_intf.from.rema  <= _27_;
  assign _09_ = _10_ ? (* full_case = 32'd1 *) (* src = "long_div_mods_test.v:63.10-63.42|long_div_mods_test.v:63.6-68.55" *) 8'h00 : \gen_for_loop[2].div_intf.from.quot ;
  assign _11_ = _12_ ? (* full_case = 32'd1 *) (* src = "long_div_mods_test.v:63.10-63.42|long_div_mods_test.v:63.6-68.55" *) 8'h00 : \gen_for_loop[2].div_intf.from.rema ;
  assign _13_ = _14_ ? (* full_case = 32'd1 *) (* src = "long_div_mods_test.v:65.15-65.52|long_div_mods_test.v:65.11-68.55" *) 1'h1 : 1'h0;
  assign _15_ = _16_ ? (* full_case = 32'd1 *) (* src = "long_div_mods_test.v:63.10-63.42|long_div_mods_test.v:63.6-68.55" *) 1'h0 : _13_;
  assign _17_ = _18_ ? (* full_case = 32'd1 *) (* src = "long_div_mods_test.v:63.10-63.42|long_div_mods_test.v:63.6-68.55" *) 8'h00 : \gen_for_loop[1].div_intf.from.quot ;
  assign _19_ = _20_ ? (* full_case = 32'd1 *) (* src = "long_div_mods_test.v:63.10-63.42|long_div_mods_test.v:63.6-68.55" *) 8'h00 : \gen_for_loop[1].div_intf.from.rema ;
  assign _21_ = _22_ ? (* full_case = 32'd1 *) (* src = "long_div_mods_test.v:65.15-65.52|long_div_mods_test.v:65.11-68.55" *) 1'h1 : 1'h0;
  assign _23_ = _24_ ? (* full_case = 32'd1 *) (* src = "long_div_mods_test.v:63.10-63.42|long_div_mods_test.v:63.6-68.55" *) 1'h0 : _21_;
  assign _25_ = _26_ ? (* full_case = 32'd1 *) (* src = "long_div_mods_test.v:63.10-63.42|long_div_mods_test.v:63.6-68.55" *) 8'h00 : \gen_for_loop[0].div_intf.from.quot ;
  assign _27_ = _28_ ? (* full_case = 32'd1 *) (* src = "long_div_mods_test.v:63.10-63.42|long_div_mods_test.v:63.6-68.55" *) 8'h00 : \gen_for_loop[0].div_intf.from.rema ;
  assign _29_ = _30_ ? (* full_case = 32'd1 *) (* src = "long_div_mods_test.v:65.15-65.52|long_div_mods_test.v:65.11-68.55" *) 1'h1 : 1'h0;
  assign _31_ = _32_ ? (* full_case = 32'd1 *) (* src = "long_div_mods_test.v:63.10-63.42|long_div_mods_test.v:63.6-68.55" *) 1'h0 : _29_;
  assign \gen_for_loop[0].div_intf.clk  = clk;
  assign \gen_for_loop[0].div_intf.rst  = rst;
  assign \gen_for_loop[0].div_intf.valid  = inp_valid[0];
  assign \gen_for_loop[0].div_intf.numer  = inp_numer[0];
  assign \gen_for_loop[0].div_intf.denom  = inp_denom[0];
  assign \gen_for_loop[0].div_intf.is_signed  = inp_is_signed[0];
  assign outp_ready[0] = \gen_for_loop[0].div_intf.ready ;
  assign outp_quot[2:0] = { 2'h0, \gen_for_loop[0].div_intf.quot  };
  assign outp_rema[2:0] = { 2'h0, \gen_for_loop[0].div_intf.rema  };
  assign \gen_for_loop[1].div_intf.clk  = clk;
  assign \gen_for_loop[1].div_intf.rst  = rst;
  assign \gen_for_loop[1].div_intf.valid  = inp_valid[1];
  assign \gen_for_loop[1].div_intf.numer  = inp_numer[3];
  assign \gen_for_loop[1].div_intf.denom  = inp_denom[3];
  assign \gen_for_loop[1].div_intf.is_signed  = inp_is_signed[1];
  assign outp_ready[1] = \gen_for_loop[1].div_intf.ready ;
  assign outp_quot[5:3] = { 2'h0, \gen_for_loop[1].div_intf.quot  };
  assign outp_rema[5:3] = { 2'h0, \gen_for_loop[1].div_intf.rema  };
  assign \gen_for_loop[2].div_intf.clk  = clk;
  assign \gen_for_loop[2].div_intf.rst  = rst;
  assign \gen_for_loop[2].div_intf.valid  = inp_valid[2];
  assign \gen_for_loop[2].div_intf.numer  = inp_numer[6];
  assign \gen_for_loop[2].div_intf.denom  = inp_denom[6];
  assign \gen_for_loop[2].div_intf.is_signed  = inp_is_signed[2];
  assign outp_ready[2] = \gen_for_loop[2].div_intf.ready ;
  assign outp_quot[8:6] = { 2'h0, \gen_for_loop[2].div_intf.quot  };
  assign outp_rema[8:6] = { 2'h0, \gen_for_loop[2].div_intf.rema  };
  assign _30_ = \gen_for_loop[2].div_intf.to.valid ;
  assign _32_ = \gen_for_loop[2].div_intf.rst ;
  assign _07_ = _31_;
  assign _10_ = \gen_for_loop[2].div_intf.rst ;
  assign _06_ = _09_;
  assign _12_ = \gen_for_loop[2].div_intf.rst ;
  assign _08_ = _11_;
  assign _14_ = \gen_for_loop[1].div_intf.to.valid ;
  assign _16_ = \gen_for_loop[1].div_intf.rst ;
  assign _04_ = _15_;
  assign _18_ = \gen_for_loop[1].div_intf.rst ;
  assign _03_ = _17_;
  assign _20_ = \gen_for_loop[1].div_intf.rst ;
  assign _05_ = _19_;
  assign _22_ = \gen_for_loop[0].div_intf.to.valid ;
  assign _24_ = \gen_for_loop[0].div_intf.rst ;
  assign _01_ = _23_;
  assign _26_ = \gen_for_loop[0].div_intf.rst ;
  assign _00_ = _25_;
  assign _28_ = \gen_for_loop[0].div_intf.rst ;
  assign _02_ = _27_;
endmodule
